### ISSUE TITLE
Filtering all incoming vars

### ISSUE THREAD

**Issue by markc** [markc/hcp#1]
This is the static method I use to currently filter incoming variables passed in via $in so if you think this level of filtering is good enough then the insecure $_POST extract could perhaps be...

    extract(util::esc($_POST));

In fact this might happen automatically if the incoming POST variables are listed in the local class $this->in variable but I haven't tested that idea.

    public static function esc(array $in) : array
    {
        foreach ($in as $k => $v)
            $in[$k] = isset($_REQUEST[$k]) && !is_array($_REQUEST[$k])
                ? htmlentities(trim($_REQUEST[$k]), ENT_QUOTES, 'UTF-8') : $v;
        return $in;
    }

**Comment by karkouch** [comment]
`extract($_POST)` appears only in one place `lib/plugins/domains.php`, especially on `Plugins_Domains::create`, and there are no variables declared before the `extract()`, also none of the superglobal variables was used in this method so at that moment `export()` will not overwrite any existing variable, but anyway the second parameter of `extract()` must be set to `EXTR_SKIP` (a flag with means If there is a collision, don't overwrite the existing variable.).

Also, I think there's no need for using `Util::esc` as it will just add a lot of extra characters to the database entries, which will make it hard to be used on other applications, so I think it's better to sanitize data against any possible XSS when gets displayed to the browser, also you're already using PDO, so there will be no SQLi.

So `extract(util::esc($_POST));` must be replaced with this `extract($_POST, EXTR_SKIP);`
